In [2]:
import numpy as np
import random

random_values = []
count = 0

while count < 20:
    random_values.append(random.randint(0, 20))
    count += 1

numpy_array = np.array([1])
numpy_array = np.append(numpy_array, random_values)
print(numpy_array)


[ 1  2  0 19  0  3 13 19  4  3  4 10 14  9 17 15 10  0 14 15 12]


In [13]:
import numpy as np

binomial_sample = np.random.binomial(n=10, p=0.3, size=15)
poisson_sample = np.random.poisson(lam=2, size=5)

print(binomial_sample)
print(poisson_sample)


[1 1 2 2 4 2 3 3 1 5 2 1 3 2 4]
[5 4 2 4 2]


In [12]:
import numpy as np

rand_matrix = np.random.uniform(size=(3, 2))
print(rand_matrix)


[[0.13182206 0.90918059]
 [0.02633191 0.46967088]
 [0.26923228 0.10611531]]


In [16]:
import numpy as np

logsamples = np.random.logistic(loc=2, scale=2, size=(2, 2))
print(logsamples)


[[10.97586344  1.75525514]
 [ 0.44861284  3.21716616]]


In [17]:
import numpy as np

def divideelementwise(arr1, arr2):
    return np.divide(arr1, arr2)

dividearrays = np.frompyfunc(divideelementwise, 2, 1)
array1 = np.array([10, 7, 3, 2])
array2 = np.array([5, 4, 9, 4])
result = dividearrays(array1, array2)
print(result)


[2.0 1.75 0.3333333333333333 0.5]


In [20]:
import numpy as np

normalsamples = np.random.normal(size=(2, 1))
print(normalsamples)


[[1.30809664]
 [0.17180555]]
