In [40]:
# q1. Write a program to create numpy array or vector of all the even integers from 20 to 50
# exluding 20 and 50.

import numpy as np

a = 22
z = 50 #since list always goes until "length-1" so 50 would be excluded automatically.

even_numbers_list = []

for num in range(a,z,2):
    even_numbers_list.append(num)

even_numbers_nparray = np.array(even_numbers_list) #converting list to np.array

print(even_numbers_nparray)

[22 24 26 28 30 32 34 36 38 40 42 44 46 48]


In [9]:
# q2. Create a multi-dimensional array of 3 rows and 3 columns having odd numbers from 1 to
# 19 including 1 and excluding 19. After that, iterate over this array to print all elements.

import numpy as np

odd = np.arange(1, 19, 2).reshape(3, 3)

for row in odd_numbers_array:
    for element in row:
        print(element, end=" ")
    print() #this will add new line after one complete iteration of the inner loop


1 3 5 
7 9 11 
13 15 17 


In [38]:
# q3. Create 3x3 matrix containing only even numbers. Multiply each element of this array with
# 4 and then multiply resultant matrix with 3x3 identity matrix (identity matrix should not be
# hardcoded).

import numpy as np

even_arr = np.arange(2,20,2).reshape(3,3) #sample matrix

print("Orignal Array is \n",even_arr)
print()

x=even_arr*4
print("Array after multiplying by 4 is \n",x)
print()

i=np.eye(3,dtype=int)

print("Identity matrix is \n",i)
print()
z=i*x
print("MATRIX after Multiplying by identity matrix is\n",z)
print()


Orignal Array is 
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Array after multiplying by 4 is 
 [[ 8 16 24]
 [32 40 48]
 [56 64 72]]

Identity matrix is 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]

MATRIX after Multiplying by identity matrix is
 [[ 8  0  0]
 [ 0 40  0]
 [ 0  0 72]]



In [36]:
# q4. Write a NumPy program to create a structured array from given student name, height, class
# and their data types. Now sort by class, then height if class are equal.

import numpy as np

dtype = [('name', 'S15'), ('height', 'float64'), ('class', int)]

data = np.array([('Ali', 160.5, 10),
                        ('Fatima', 175.2, 12),
                        ('Zahid', 150.3, 10),
                        ('Sana', 172.7, 11),
                        ('Ahmed', 160.5, 12)],
                        dtype=dtype)

print("Original Array\n", data)

sorted= np.sort(data, order=['class', 'height'])

print("\nSorted Array by class and then by height if classes are equal:\n", sorted)


Original Array
 [(b'Ali', 160.5, 10) (b'Fatima', 175.2, 12) (b'Zahid', 150.3, 10)
 (b'Sana', 172.7, 11) (b'Ahmed', 160.5, 12)]

Sorted Array by class and then by height if classes are equal:
 [(b'Zahid', 150.3, 10) (b'Ali', 160.5, 10) (b'Sana', 172.7, 11)
 (b'Ahmed', 160.5, 12) (b'Fatima', 175.2, 12)]


In [51]:
# q5. Generate 4x4 matrix with random numbers only from (2,5,9,10) and then multiply this
# matrix with identity matrix. Finally add this matrix to any 4x4 matrix having only odd
# numbers.

import numpy as np
from numpy import random as r

x=r.choice([2,5,9,10],size=(4,4))
print("Random array generated from given list is:\n",x)

i=np.eye(4,dtype=int)
z=i*x
print("After multiplying the random array with identity matrix we get:\n",z)

odd=np.arange(1,33,2).reshape(4,4)#33will be excluded bcz array is always length-1
print("Matrix of odd integers:\n",odd)
print("Adding this matrix to an odd matrix we get:\n",odd+z)


Random array generated from given list is:
 [[ 9  2  2 10]
 [ 2 10  5  9]
 [ 5 10 10  9]
 [ 2  2  5  2]]
After multiplying the random array with identity matrix we get:
 [[ 9  0  0  0]
 [ 0 10  0  0]
 [ 0  0 10  0]
 [ 0  0  0  2]]
Matrix of odd integers:
 [[ 1  3  5  7]
 [ 9 11 13 15]
 [17 19 21 23]
 [25 27 29 31]]
Adding this matrix to an odd matrix we get:
 [[10  3  5  7]
 [ 9 21 13 15]
 [17 19 31 23]
 [25 27 29 33]]


In [69]:
# q6. Write a NumPy program to multiply a 5x3 matrix by a 3x2.

import numpy as np
from numpy import random as r
#SYNTAAX[min_value, max_value,array_size=(x,y)]
a = np.random.randint(1, 10, size=(5, 3))#we cant use keyword r for random IF we are already using a keyword for np.
                                         #we have to call it by its fullname i.e random
                                         #so either the "a=r.randint(1,10,size(5,3))" or "a=np.random.randint(1,10,size(5,3))
b= np.random.randint(11, 20, size=(3, 2))

result = np.dot(a, b)#used for matrix multiplication

print("Random Matrix A of size(5x3):\n", a)
print("\nRandom Matrix B of size(3x2):\n", b)
print("\nResult Matrix (5x2) after multiplication:\n", result)


Random Matrix A of size(5x3):
 [[9 5 6]
 [6 7 3]
 [3 4 5]
 [6 1 1]
 [5 6 2]]

Random Matrix B of size(3x2):
 [[19 17]
 [12 11]
 [12 12]]

Result Matrix (5x2) after multiplication:
 [[303 280]
 [234 215]
 [165 155]
 [138 125]
 [191 175]]


In [107]:
# q7. Write a NumPy program to create a random array with 1000 elements and compute the
# average, variance, standard deviation of the array elements. Save all the results in text file
# created at runtime.

import numpy as np

arr = np.random.randint(1000, 2000+1, size=1000).reshape(-1, 10)#2000+1 so that 2000 also gets included

avg = np.average(arr)
var = np.var(arr)
std = np.std(arr)

# Convert the original array to a string too make it look more readable in the file.
new_arr = str(arr)

with open("results.txt", 'w') as file:
    file.write("Original Array:\n")
    file.write(new_arr + '\n')
    file.write(f"Average: {avg}\n")
    file.write(f"Variance: {var}\n")
    file.write(f"Standard Deviation: {std}\n")


print("Displaying only the first 5 rows of the random array:\n", arr[:5])
print("\nAverage of random array was found to be:", avg)
print("\nVariance of random array was found to be:", var)
print("\nStandard Deviation of random array was found to be:", std)
print("\nResults and original array saved to", "results.txt")


Displaying only the first 5 rows of the random array:
 [[1011 1301 1326 1880 1201 1151 1383 1186 1846 1307]
 [1587 1886 1889 1349 1196 1440 1775 1076 1797 1179]
 [1310 1520 1020 1452 1758 1642 1247 1505 1928 1213]
 [1802 1649 1829 1502 1466 1352 1726 1560 1384 1464]
 [1078 1279 1872 1496 1576 1860 1214 1159 1893 1753]]

Average of random array was found to be: 1506.225

Variance of random array was found to be: 82879.130375

Standard Deviation of random array was found to be: 287.8873570947498

Results and original array saved to results.txt
